apiVersion: batch/v1
kind: Job
metadata:
  name: fortio-load
  namespace: bench
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        ambient.istio.io/redirection: disabled
    spec:
      nodeSelector:
        bench-role: client
      restartPolicy: Never
      containers:
        - name: fortio
          image: fortio/fortio:1.66.0
          command:
            - fortio
            - load
            - -json
            - /dev/stdout
            - -quiet
            - -qps
            - "${QPS}"
            - -c
            - "${CONNECTIONS}"
            - -timeout
            - "${FORTIO_TIMEOUT}s"
            - -t
            - "${DURATION}s"
            - -payload-size
            - "${PAYLOAD_SIZE}"
            - -labels
            - "${LABEL}"
            - http://echo-server:8080/echo
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
